src/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("send_login_email", views.send_login_email, name="send_login_email"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
]

src/lists/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path("new", views.new_list, name="new_list"),
    path("<int:list_id>/", views.view_list, name="view_list"),
    re_path(r"^users/(.+)/", views.my_lists, name="my_lists"),
]

src/superlists/urls.py
from django.contrib import admin
from django.urls import path, include
from lists import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home_page, name="home"),
    path("lists/", include("lists.urls")),
    path("accounts/", include("accounts.urls")),
]

src/accounts/models.py
from django.db import models
import uuid


class User(models.Model):
    email = models.EmailField(unique=True, primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = "email"
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

src/lists/models.py
from django.db.models.deletion import CASCADE
from django.db import models
from django.urls import reverse
from django.db.models.constraints import UniqueConstraint

# Create your models here.


class List(models.Model):
    def get_absolute_url(self):
        return reverse("view_list", args=[self.pk])


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default="", on_delete=models.CASCADE)

    class Meta:
        constraints = [
            UniqueConstraint(fields=["text", "list"], name="unique_item"),
        ]
        ordering = [
            "id",
        ]

    def __str__(self):
        return self.text


class Item1(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default="", on_delete=models.CASCADE)

src/lists/forms.py
from django import forms

from lists.models import Item, List
from django.core.exceptions import ValidationError

_EMPTY_ITEM_ERROR = "You can't have an empty list item"
_DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ("text",)
        widgets = {
            "text": forms.TextInput(
                attrs={
                    "placeholder": "Enter a to-do item",
                    "class": "form-control input-lg",
                }
            ),
        }
        error_messages = {"text": {"required": _EMPTY_ITEM_ERROR}}

    def save(self, for_list: List):
        self.instance.list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {"text": [_DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.ModelForm.save(self)

src/accounts/views.py
from accounts.models import Token
from django.http.request import HttpRequest, QueryDict
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.contrib import messages, auth
from django.urls import reverse
import sys


def send_login_email(request: HttpRequest):
    email = request.POST.get("email", "")
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(reverse("login") + "?token=" + str(token.uid))
    message_body = f"Use this link to log in:\n\n{url}"
    send_mail("Your login link for Superlists", message_body, "noreply@superlists", [email])
    messages.success(request, "Check your email, we've sent you a link you can use to log in.")
    return redirect("/")


def login(request: HttpRequest):
    user = auth.authenticate(request=request, uid=request.GET.get("token"))
    if user:
        print("udało się", file=sys.stderr)
        auth.login(request, user)
    else:
        print("błąd", file=sys.stderr)
    return redirect("/")


def logout(request: HttpRequest):
    auth.logout(request)
    return redirect("/")

src/lists/views.py
from lists.forms import ItemForm
from typing import Union

from django.core.exceptions import ValidationError
from django.db.models.expressions import Combinable
from django.http.request import HttpRequest, QueryDict
from django.http.response import HttpResponse
from django.shortcuts import redirect, render

from lists.forms import ItemForm, ExistingListItemForm
from lists.models import Item, List


# Create your views here.
def home_page(request: HttpRequest) -> HttpResponse:
    return render(request, "home.html", {"form": ItemForm()})


def view_list(request: HttpRequest, list_id: int) -> HttpResponse:
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == "POST":
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)

    return render(request, "list.html", {"list": list_, "form": form})


def new_list(request: HttpRequest) -> HttpResponse:
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(list_)
        return redirect(list_)
    else:
        return render(request, "home.html", {"form": form})


def my_lists(request: HttpRequest, email):
    return render(request, "my_lists.html")

src/lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>To-Do lists</title>
  <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/base.css">
  <script src="/static/jquery-3.4.1.min.js"></script>
  <script src="/static/list.js"></script>
</head>

<body>

  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Superlists</a>
        {% if user.email %}
        <ul class="nav navbar-nav navbar-left">
          <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="navbar-text">Logged in as {{ user.email }}</li>
          <li><a href=" {% url 'logout' %} ">Log out</a></li>
        </ul>
        {% else %}
        <form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
          <span>Enter email to log in:</span>
          <input class="form-control" name="email" type="text" />
          {% csrf_token %}
        </form>
        {% endif %}
      </div>
    </nav>

    {% if messages %}
    <div class="row">
      <div class="col-md-8">
        {% for message in messages %}
        {% if message.level_tag == 'success' %}
        <div class="alert alert-success">{{ message }}</div>
        {% else %}
        <div class="alert alert-warning">{{ message }}</div>
        {% endif %}
        {% endfor %}
      </div>
    </div>
    {% endif %}


    <div class="row justify-content-md-center">
      <div class="col jumbotron">
        <div class="text-center">
          <h1> {% block header_text %}{% endblock %}</h1>
          {% block list_form %}
          <form method="POST" action=" {% block form_action %}{% endblock %}">
            {{ form.text }}
            {% csrf_token %}
            {% if form.errors %}
            <div class="form-group has-error">
              <span class="help-block">{{ form.text.errors }}</span>
            </div>
            {% endif %}
          </form>
          {% endblock %}

        </div>
      </div>
    </div>
    <div class="row justify-content-md-center">
      <div class="col">
        {% block table %}
        {% endblock  %}
      </div>
    </div>
    <div class="row justify-content-md-center">
      <div class="col-md-6 col-md-offset-3">
        {% block extra_content %}
        {% endblock %}
      </div>
    </div>

  </div>


  <script>
    initialize();
  </script>
</body>

</html>

src/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

src/lists/templates/list.html
{% extends 'base.html' %}
{% block header_text %}Your To-Do list{% endblock %}
{% block form_action %}{% url 'view_list' list.pk %}{% endblock %}



{% block table %}
<table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
    <tr>
        <td>{{ forloop.counter }}: {{ item.text }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock  %}

src/lists/templates/my_lists.html
{% extends 'base.html' %}
{% block header_text %}My Lists{% endblock %}
{% block list_form %}{% endblock %}
{% block extra_content %}
<h2>{{ owner.email }}'s lists</h2>
<ul>
    {% for list in owner.list_set.all %}
    <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}